#!/bin/bash -e

git fetch --tags -p

VERSION=$(git describe --tag --abbrev=0 --match *-rc*)

echo The most recent tag that is reachable by this commit is $VERSION

read VERSION_MAJOR VERSION_PATCH <<< $(IFS="-rc"; echo $VERSION)
NEW_VERSION=$VERSION_MAJOR-rc$(($VERSION_PATCH+1))

echo The new tag will be $NEW_VERSION
git config --global user.email "luceoplatformintegrity@careerbuilder.com"
git config --global user.name "Luceo Deployment"
git tag -a $NEW_VERSION -m ''
git push origin $NEW_VERSION
